import type { AppData } from "./types";

const daysAgo = (n: number, hour = 21) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 30, 0, 0);
  return d.toISOString();
};

export const defaultAppData: AppData = {
  questions: [
    {
      id: "q1",
      name: "Minimum Window Substring",
      topic: "Arrays & Hashing",
      difficulty: "hard",
      pattern: "Sliding Window",
      trigger: "State = index, not substring",
      confidence: 3,
      reflection: "I forgot to shrink window when duplicate characters appear.",
      mistakes: ["Used BFS instead of DFS", "Forgot to remove characters while shrinking"],
      insights: ["Shrink when map size exceeds k", "Track char frequency in hash map"],
      solvedAt: daysAgo(11, 22),
      lastRevisedAt: daysAgo(4),
      timeTaken: 45,
    },
    {
      id: "q2",
      name: "Longest Repeating Character Replacement",
      topic: "Arrays & Hashing",
      difficulty: "medium",
      pattern: "Sliding Window",
      trigger: "Window size - maxFreq <= k",
      confidence: 4,
      reflection: "I forgot to remove characters from the set while shrinking the window.",
      mistakes: ["Did not update max frequency correctly"],
      insights: ["Track max frequency in window", "Shrink when invalid"],
      solvedAt: daysAgo(8, 21),
      lastRevisedAt: daysAgo(2),
      timeTaken: 32,
    },
    {
      id: "q3",
      name: "Word Break",
      topic: "Dynamic Programming",
      difficulty: "hard",
      pattern: "Dynamic Programming",
      trigger: "State = index, not substring",
      confidence: 3,
      reflection: "DP[i] means string till i can be segmented.",
      mistakes: ["Started recursion first", "Forgot memoization"],
      insights: ["Build state before coding", "Check dictionary at each split"],
      solvedAt: daysAgo(15, 20),
      lastRevisedAt: daysAgo(12),
      timeTaken: 55,
    },
    {
      id: "q4",
      name: "Rotting Oranges",
      topic: "Graphs",
      difficulty: "medium",
      pattern: "Graphs",
      trigger: "Multi-source BFS",
      confidence: 4,
      reflection: "Push all rotten oranges first before BFS.",
      mistakes: ["Visited state mistake in BFS", "Forgot visited check"],
      insights: ["Multi-source BFS from all rotten", "Track minutes per level"],
      solvedAt: daysAgo(5, 22),
      lastRevisedAt: daysAgo(1),
      timeTaken: 28,
    },
    {
      id: "q5",
      name: "Implement Trie",
      topic: "Trie",
      difficulty: "medium",
      pattern: "Trie",
      trigger: "Node per character, isEnd flag",
      confidence: 2,
      reflection: "Forgot to mark isEnd on insert.",
      mistakes: ["Did not handle prefix vs word", "Null pointer on empty trie"],
      insights: ["26 children array or map", "Track isEnd separately"],
      solvedAt: daysAgo(42, 19),
      lastRevisedAt: daysAgo(35),
      timeTaken: 40,
    },
    {
      id: "q6",
      name: "House Robber",
      topic: "Dynamic Programming",
      difficulty: "medium",
      pattern: "Dynamic Programming",
      trigger: "DP state = max money at index i",
      confidence: 4,
      reflection: "State is max money including or excluding current house.",
      mistakes: ["Used greedy instead of DP"],
      insights: ["dp[i] = max(dp[i-1], dp[i-2] + nums[i])"],
      solvedAt: daysAgo(34, 21),
      lastRevisedAt: daysAgo(20),
      timeTaken: 25,
    },
    {
      id: "q7",
      name: "Longest Palindrome",
      topic: "Two Pointer",
      difficulty: "medium",
      pattern: "Two Pointer",
      trigger: "Expand from center",
      confidence: 5,
      reflection: "Check odd and even centers separately.",
      mistakes: [],
      insights: ["Expand around each center", "Track max length"],
      solvedAt: daysAgo(3, 22),
      lastRevisedAt: daysAgo(1),
      timeTaken: 22,
    },
    {
      id: "q8",
      name: "Course Schedule II",
      topic: "Graphs",
      difficulty: "medium",
      pattern: "Graphs",
      trigger: "Topological sort via Kahn's",
      confidence: 2,
      reflection: "Cycle detection needed before topo sort.",
      mistakes: ["Did not detect cycle", "Wrong indegree initialization"],
      insights: ["Kahn's algorithm with queue", "Check result length vs n"],
      solvedAt: daysAgo(9, 20),
      lastRevisedAt: daysAgo(9),
      timeTaken: 38,
    },
  ],
  patterns: [
    {
      id: "p1",
      name: "Sliding Window",
      description:
        "Optimize contiguous subarray and substring problems using dynamic boundaries.",
      tags: ["Substring", "Contiguous", "Two Pointer"],
      status: "Strong",
    },
    {
      id: "p2",
      name: "Graphs",
      description: "Model relationships and connectivity using nodes and edges.",
      tags: ["BFS", "DFS", "Traversal"],
      status: "Medium",
    },
    {
      id: "p3",
      name: "Trie",
      description: "Prefix tree for efficient string lookups and autocomplete.",
      tags: ["Prefix", "Strings", "Tree"],
      status: "Weak",
    },
    {
      id: "p4",
      name: "Dynamic Programming",
      description: "Break complex problems into reusable overlapping subproblems.",
      tags: ["Memoization", "Tabulation", "States"],
      status: "Medium",
    },
    {
      id: "p5",
      name: "Two Pointer",
      description: "Use two indices to scan arrays efficiently.",
      tags: ["Sorted", "Palindrome", "Window"],
      status: "Strong",
    },
    {
      id: "p6",
      name: "Binary Search",
      description: "Reduce search space by half at every step.",
      tags: ["Sorted Array", "Search", "LogN"],
      status: "Weak",
    },
  ],
  activities: [
    {
      id: "a1",
      type: "solved",
      text: "Solved",
      highlight: "Longest Palindrome",
      date: daysAgo(0, 22),
    },
    {
      id: "a2",
      type: "quiz-score",
      text: "Quiz Score",
      highlight: "8/10",
      date: daysAgo(0, 20),
    },
    {
      id: "a3",
      type: "revision-completed",
      text: "Revision Completed",
      highlight: "Rotting Oranges",
      date: daysAgo(1, 21),
    },
    {
      id: "a4",
      type: "reflection",
      text: "Reflection Added",
      highlight: "Longest Repeating Character Replacement",
      date: daysAgo(1, 19),
    },
    {
      id: "a5",
      type: "pattern-mastered",
      text: "Pattern Mastered",
      highlight: "Two Pointer",
      date: daysAgo(2, 22),
    },
    {
      id: "a6",
      type: "revised",
      text: "Revised",
      highlight: "Graphs",
      date: daysAgo(2, 20),
    },
    {
      id: "a7",
      type: "mistake",
      text: "Forgot",
      highlight: "Trie Pattern",
      date: daysAgo(3, 18),
    },
    {
      id: "a8",
      type: "quiz-score",
      text: "Quiz Score",
      highlight: "7/10",
      date: daysAgo(4, 21),
    },
  ],
  revisionQueue: [
    { id: "rq1", type: "question", title: "Minimum Window Substring", completed: false, skipped: false, reviewAgain: false },
    { id: "rq2", type: "question", title: "Longest Repeating Character Replacement", completed: false, skipped: false, reviewAgain: false },
    { id: "rq3", type: "pattern", title: "Trie Pattern", completed: false, skipped: false, reviewAgain: false },
    { id: "rq4", type: "pattern", title: "Graph Traversal", completed: false, skipped: false, reviewAgain: false },
    { id: "rq5", type: "reflection", title: "Window shrinking condition", completed: false, skipped: false, reviewAgain: false },
    { id: "rq6", type: "question", title: "Course Schedule II", completed: false, skipped: false, reviewAgain: false },
    { id: "rq7", type: "question", title: "Implement Trie", completed: false, skipped: false, reviewAgain: false },
  ],
  quizResults: [
    { id: "qr1", date: daysAgo(0), score: 8, total: 10 },
    { id: "qr2", date: daysAgo(1), score: 7, total: 10 },
    { id: "qr3", date: daysAgo(2), score: 9, total: 10 },
    { id: "qr4", date: daysAgo(3), score: 6, total: 10 },
    { id: "qr5", date: daysAgo(4), score: 8, total: 10 },
    { id: "qr6", date: daysAgo(5), score: 7, total: 10 },
    { id: "qr7", date: daysAgo(6), score: 9, total: 10 },
  ],
  dailyChallengeIndex: 0,
  dailyChallengeDate: new Date().toISOString().slice(0, 10),
};
