import type { AppData } from "./types";

const daysAgo = (n: number, hour = 21) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 30, 0, 0);
  return d.toISOString();
};

const daysFromNow = (n: number, hour = 21) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(hour, 30, 0, 0);
  return d.toISOString();
};

export const defaultAppData: AppData = {
  questions: [
    {
      id: "q1",
      name: "Minimum Window Substring",
      topic: "Sliding Window",
      difficulty: "hard",
      pattern: "Sliding Window",
      trigger: "State = index, not substring",
      confidence: 3,
      reflection: "I forgot to shrink window when duplicate characters appear.",
      mistakes: ["Used BFS instead of DFS", "Forgot to remove characters while shrinking"],
      insights: ["Shrink when map size exceeds k", "Track char frequency in hash map"],
      solvedAt: daysAgo(11, 22),
      lastRevisedAt: daysAgo(4),
      timeTaken: 45,
      revisionStar: 2,
      nextRevisionAt: daysAgo(1),
    },
    {
      id: "q2",
      name: "Longest Repeating Character Replacement",
      topic: "Sliding Window",
      difficulty: "medium",
      pattern: "Sliding Window",
      trigger: "Window size - maxFreq <= k",
      confidence: 4,
      reflection: "I forgot to remove characters from the set while shrinking the window.",
      mistakes: ["Did not update max frequency correctly"],
      insights: ["Track max frequency in window", "Shrink when invalid"],
      solvedAt: daysAgo(8, 21),
      lastRevisedAt: daysAgo(2),
      timeTaken: 32,
      revisionStar: 3,
      nextRevisionAt: daysFromNow(5),
    },
    {
      id: "q9",
      name: "Longest Substring Without Repeating Characters",
      topic: "Sliding Window",
      difficulty: "medium",
      pattern: "Sliding Window",
      trigger: "Hashmap of last-seen index",
      confidence: 5,
      reflection: "Shrink window whenever a duplicate's last seen index falls inside it.",
      mistakes: [],
      insights: ["Track last index of each character", "Move left pointer past the duplicate"],
      solvedAt: daysAgo(2, 22),
      lastRevisedAt: daysAgo(0),
      timeTaken: 18,
      revisionStar: 4,
      nextRevisionAt: daysFromNow(13),
    },
    {
      id: "q4",
      name: "Rotting Oranges",
      topic: "Graphs",
      difficulty: "medium",
      pattern: "Graphs",
      trigger: "Multi-source BFS",
      confidence: 4,
      reflection: "Push all rotten oranges first before BFS.",
      mistakes: ["Visited state mistake in BFS", "Forgot visited check"],
      insights: ["Multi-source BFS from all rotten", "Track minutes per level"],
      solvedAt: daysAgo(5, 22),
      lastRevisedAt: daysAgo(1),
      timeTaken: 28,
      revisionStar: 1,
      nextRevisionAt: daysAgo(0),
    },
    {
      id: "q8",
      name: "Course Schedule II",
      topic: "Graphs",
      difficulty: "medium",
      pattern: "Graphs",
      trigger: "Topological sort via Kahn's",
      confidence: 2,
      reflection: "Cycle detection needed before topo sort.",
      mistakes: ["Did not detect cycle", "Wrong indegree initialization"],
      insights: ["Kahn's algorithm with queue", "Check result length vs n"],
      solvedAt: daysAgo(9, 20),
      lastRevisedAt: daysAgo(9),
      timeTaken: 38,
      revisionStar: 1,
      nextRevisionAt: daysAgo(8),
    },
    {
      id: "q10",
      name: "Number of Islands",
      topic: "Graphs",
      difficulty: "medium",
      pattern: "Graphs",
      trigger: "DFS/BFS flood fill, mark visited",
      confidence: 4,
      reflection: "Flood fill each unvisited land cell and count separate fills.",
      mistakes: ["Forgot to mark visited before recursing, caused infinite loop"],
      insights: ["Mark visited immediately on entry", "Count fills, not cells"],
      solvedAt: daysAgo(6, 21),
      lastRevisedAt: daysAgo(3),
      timeTaken: 24,
      revisionStar: 2,
      nextRevisionAt: daysAgo(0),
    },
    {
      id: "q5",
      name: "Implement Trie",
      topic: "Trie",
      difficulty: "medium",
      pattern: "Trie",
      trigger: "Node per character, isEnd flag",
      confidence: 2,
      reflection: "Forgot to mark isEnd on insert.",
      mistakes: ["Did not handle prefix vs word", "Null pointer on empty trie"],
      insights: ["26 children array or map", "Track isEnd separately"],
      solvedAt: daysAgo(42, 19),
      lastRevisedAt: daysAgo(35),
      timeTaken: 40,
      revisionStar: 1,
      nextRevisionAt: daysAgo(34),
    },
    {
      id: "q11",
      name: "Word Search II",
      topic: "Trie",
      difficulty: "hard",
      pattern: "Trie",
      trigger: "Build trie of words, DFS board with pruning",
      confidence: 3,
      reflection: "Prune trie nodes once a word is found to speed up search.",
      mistakes: ["Rebuilt trie per cell instead of once upfront", "Forgot to remove found word to prevent duplicate matches"],
      insights: ["Build trie once from word list", "Backtrack board visited state"],
      solvedAt: daysAgo(20, 20),
      lastRevisedAt: daysAgo(15),
      timeTaken: 62,
      revisionStar: 2,
      nextRevisionAt: daysAgo(12),
    },
    {
      id: "q3",
      name: "Word Break",
      topic: "Dynamic Programming",
      difficulty: "hard",
      pattern: "Dynamic Programming",
      trigger: "State = index, not substring",
      confidence: 3,
      reflection: "DP[i] means string till i can be segmented.",
      mistakes: ["Started recursion first", "Forgot memoization"],
      insights: ["Build state before coding", "Check dictionary at each split"],
      solvedAt: daysAgo(15, 20),
      lastRevisedAt: daysAgo(12),
      timeTaken: 55,
      revisionStar: 2,
      nextRevisionAt: daysAgo(9),
    },
    {
      id: "q6",
      name: "House Robber",
      topic: "Dynamic Programming",
      difficulty: "medium",
      pattern: "Dynamic Programming",
      trigger: "DP state = max money at index i",
      confidence: 4,
      reflection: "State is max money including or excluding current house.",
      mistakes: ["Used greedy instead of DP"],
      insights: ["dp[i] = max(dp[i-1], dp[i-2] + nums[i])"],
      solvedAt: daysAgo(34, 21),
      lastRevisedAt: daysAgo(20),
      timeTaken: 25,
      revisionStar: 4,
      nextRevisionAt: daysAgo(5),
    },
    {
      id: "q12",
      name: "Coin Change",
      topic: "Dynamic Programming",
      difficulty: "medium",
      pattern: "Dynamic Programming",
      trigger: "dp[i] = min coins to make amount i",
      confidence: 3,
      reflection: "Bottom-up dp array initialized to infinity except dp[0] = 0.",
      mistakes: ["Tried greedy first, failed on non-canonical coin sets"],
      insights: ["dp[i] = min(dp[i], dp[i-coin]+1) for each coin"],
      solvedAt: daysAgo(7, 21),
      lastRevisedAt: daysAgo(2),
      timeTaken: 33,
      revisionStar: 3,
      nextRevisionAt: daysFromNow(5),
    },
    {
      id: "q7",
      name: "Longest Palindrome",
      topic: "Two Pointer",
      difficulty: "medium",
      pattern: "Two Pointer",
      trigger: "Expand from center",
      confidence: 5,
      reflection: "Check odd and even centers separately.",
      mistakes: [],
      insights: ["Expand around each center", "Track max length"],
      solvedAt: daysAgo(3, 22),
      lastRevisedAt: daysAgo(1),
      timeTaken: 22,
      revisionStar: 5,
      nextRevisionAt: daysFromNow(29),
    },
    {
      id: "q13",
      name: "Container With Most Water",
      topic: "Two Pointer",
      difficulty: "medium",
      pattern: "Two Pointer",
      trigger: "Move pointer with smaller height inward",
      confidence: 4,
      reflection: "Moving the taller pointer can never increase area, so always move the shorter one.",
      mistakes: [],
      insights: ["Area limited by shorter wall", "Move shorter pointer inward"],
      solvedAt: daysAgo(4, 21),
      lastRevisedAt: daysAgo(1),
      timeTaken: 15,
      revisionStar: 3,
      nextRevisionAt: daysFromNow(6),
    },
    {
      id: "q14",
      name: "Search in Rotated Sorted Array",
      topic: "Binary Search",
      difficulty: "medium",
      pattern: "Binary Search",
      trigger: "Identify which half is sorted, check target range",
      confidence: 2,
      reflection: "One half of the array is always sorted; check if target lies in it.",
      mistakes: ["Confused which half was sorted", "Off-by-one on boundary comparison"],
      insights: ["Compare mid with left/right to find sorted half", "Narrow range based on sorted half"],
      solvedAt: daysAgo(13, 20),
      lastRevisedAt: daysAgo(10),
      timeTaken: 35,
      revisionStar: 1,
      nextRevisionAt: daysAgo(9),
    },
    {
      id: "q15",
      name: "Find Minimum in Rotated Sorted Array",
      topic: "Binary Search",
      difficulty: "medium",
      pattern: "Binary Search",
      trigger: "Compare mid with right to find rotation point",
      confidence: 3,
      reflection: "If nums[mid] > nums[right], minimum is to the right of mid.",
      mistakes: ["Compared mid with left instead of right"],
      insights: ["Compare mid to right boundary", "Shrink search space towards rotation point"],
      solvedAt: daysAgo(13, 20),
      lastRevisedAt: daysAgo(10),
      timeTaken: 20,
      revisionStar: 2,
      nextRevisionAt: daysAgo(7),
    },
    {
      id: "q16",
      name: "Subsets",
      topic: "Backtracking",
      difficulty: "medium",
      pattern: "Backtracking",
      trigger: "Include/exclude each element recursively",
      confidence: 4,
      reflection: "Each element has two choices: include or exclude, branching factor 2^n.",
      mistakes: [],
      insights: ["Base case at index == n", "Push a copy of the path, not a reference"],
      solvedAt: daysAgo(16, 21),
      lastRevisedAt: daysAgo(14),
      timeTaken: 20,
      revisionStar: 3,
      nextRevisionAt: daysAgo(7),
    },
    {
      id: "q17",
      name: "Word Search",
      topic: "Backtracking",
      difficulty: "hard",
      pattern: "Backtracking",
      trigger: "DFS from each cell, backtrack visited mark",
      confidence: 2,
      reflection: "Forgot to unmark the visited cell after backtracking, which corrupted later searches.",
      mistakes: ["Did not backtrack the visited flag", "Missed boundary check before recursing"],
      insights: ["Unmark the cell after DFS returns", "Check bounds before every recursive call"],
      solvedAt: daysAgo(25, 20),
      lastRevisedAt: daysAgo(18),
      timeTaken: 48,
      revisionStar: 1,
      nextRevisionAt: daysAgo(17),
    },
    {
      id: "q18",
      name: "Valid Parentheses",
      topic: "Stack",
      difficulty: "easy",
      pattern: "Stack",
      trigger: "Push open brackets, pop and match on close",
      confidence: 5,
      reflection: "Use a stack; push opens, on close pop and verify the match.",
      mistakes: [],
      insights: ["Map closing to opening bracket", "Stack empty at end means valid"],
      solvedAt: daysAgo(30, 22),
      lastRevisedAt: daysAgo(25),
      timeTaken: 8,
      revisionStar: 5,
      nextRevisionAt: daysFromNow(5),
    },
    {
      id: "q19",
      name: "Daily Temperatures",
      topic: "Stack",
      difficulty: "medium",
      pattern: "Stack",
      trigger: "Monotonic decreasing stack of indices",
      confidence: 3,
      reflection: "Keep a stack of indices with decreasing temperatures; pop when a warmer day appears.",
      mistakes: ["Stored temperatures instead of indices, couldn't compute distance"],
      insights: ["Store indices, not values", "Pop while current > stack top"],
      solvedAt: daysAgo(10, 21),
      lastRevisedAt: daysAgo(5),
      timeTaken: 27,
      revisionStar: 2,
      nextRevisionAt: daysAgo(2),
    },
    {
      id: "q20",
      name: "Reverse Linked List",
      topic: "Linked List",
      difficulty: "easy",
      pattern: "Linked List",
      trigger: "Track prev, curr, next pointers",
      confidence: 5,
      reflection: "Iteratively reverse by holding next before breaking the link.",
      mistakes: [],
      insights: ["Save next before reassigning curr.next", "Return prev as the new head"],
      solvedAt: daysAgo(40, 22),
      lastRevisedAt: daysAgo(33),
      timeTaken: 10,
      revisionStar: 5,
      nextRevisionAt: daysAgo(3),
    },
    {
      id: "q21",
      name: "Merge Two Sorted Lists",
      topic: "Linked List",
      difficulty: "easy",
      pattern: "Linked List",
      trigger: "Dummy head, compare and attach smaller node",
      confidence: 4,
      reflection: "Use a dummy node to simplify head handling.",
      mistakes: ["Forgot to attach remaining nodes after one list was exhausted"],
      insights: ["A dummy node simplifies edge cases", "Attach the leftover list directly at the end"],
      solvedAt: daysAgo(28, 21),
      lastRevisedAt: daysAgo(20),
      timeTaken: 14,
      revisionStar: 4,
      nextRevisionAt: daysAgo(5),
    },
    {
      id: "q22",
      name: "Kth Largest Element in an Array",
      topic: "Heap / Priority Queue",
      difficulty: "medium",
      pattern: "Heap / Priority Queue",
      trigger: "Min-heap of size k",
      confidence: 3,
      reflection: "Maintain a min-heap of size k; the root is the kth largest.",
      mistakes: ["Used a max-heap of all elements, wasting memory and time"],
      insights: ["A min-heap of size k is sufficient", "Pop when the heap exceeds size k"],
      solvedAt: daysAgo(12, 20),
      lastRevisedAt: daysAgo(6),
      timeTaken: 22,
      revisionStar: 2,
      nextRevisionAt: daysAgo(3),
    },
    {
      id: "q23",
      name: "Top K Frequent Elements",
      topic: "Heap / Priority Queue",
      difficulty: "medium",
      pattern: "Heap / Priority Queue",
      trigger: "Frequency map + bucket sort",
      confidence: 4,
      reflection: "Bucket sort by frequency avoids O(n log n) heap operations.",
      mistakes: [],
      insights: ["Bucket index = frequency, max bucket = n", "Iterate buckets from high to low"],
      solvedAt: daysAgo(6, 21),
      lastRevisedAt: daysAgo(2),
      timeTaken: 26,
      revisionStar: 3,
      nextRevisionAt: daysFromNow(5),
    },
  ],
  patterns: [
    {
      id: "p1",
      name: "Sliding Window",
      description:
        "Optimize contiguous subarray and substring problems using dynamic boundaries.",
      tags: ["Substring", "Contiguous", "Two Pointer"],
      status: "Strong",
    },
    {
      id: "p2",
      name: "Graphs",
      description: "Model relationships and connectivity using nodes and edges.",
      tags: ["BFS", "DFS", "Traversal"],
      status: "Medium",
    },
    {
      id: "p3",
      name: "Trie",
      description: "Prefix tree for efficient string lookups and autocomplete.",
      tags: ["Prefix", "Strings", "Tree"],
      status: "Weak",
    },
    {
      id: "p4",
      name: "Dynamic Programming",
      description: "Break complex problems into reusable overlapping subproblems.",
      tags: ["Memoization", "Tabulation", "States"],
      status: "Medium",
    },
    {
      id: "p5",
      name: "Two Pointer",
      description: "Use two indices to scan arrays efficiently.",
      tags: ["Sorted", "Palindrome", "Window"],
      status: "Strong",
    },
    {
      id: "p6",
      name: "Binary Search",
      description: "Reduce search space by half at every step.",
      tags: ["Sorted Array", "Search", "LogN"],
      status: "Weak",
    },
    {
      id: "p7",
      name: "Backtracking",
      description: "Explore all candidates and undo choices that don't lead to a solution.",
      tags: ["Recursion", "Pruning", "Combinatorics"],
      status: "Medium",
    },
    {
      id: "p8",
      name: "Stack",
      description: "LIFO structure for matching, monotonic, and nested problems.",
      tags: ["Monotonic", "Matching", "LIFO"],
      status: "Medium",
    },
    {
      id: "p9",
      name: "Linked List",
      description: "Pointer manipulation for singly and doubly linked structures.",
      tags: ["Pointers", "In-place", "Traversal"],
      status: "Strong",
    },
    {
      id: "p10",
      name: "Heap / Priority Queue",
      description: "Maintain ordered access to the min or max element efficiently.",
      tags: ["Top K", "Ordering", "O(log n)"],
      status: "Medium",
    },
  ],
  activities: [
    {
      id: "a1",
      type: "solved",
      text: "Solved",
      highlight: "Longest Substring Without Repeating Characters",
      date: daysAgo(0, 22),
    },
    {
      id: "a2",
      type: "quiz-score",
      text: "Quiz Score",
      highlight: "8/10",
      date: daysAgo(0, 20),
    },
    {
      id: "a3",
      type: "revision-completed",
      text: "Revision Completed",
      highlight: "Rotting Oranges",
      date: daysAgo(1, 21),
    },
    {
      id: "a4",
      type: "reflection",
      text: "Reflection Added",
      highlight: "Longest Repeating Character Replacement",
      date: daysAgo(1, 19),
    },
    {
      id: "a5",
      type: "pattern-mastered",
      text: "Pattern Mastered",
      highlight: "Two Pointer",
      date: daysAgo(2, 22),
    },
    {
      id: "a6",
      type: "revised",
      text: "Revised",
      highlight: "Number of Islands",
      date: daysAgo(2, 20),
    },
    {
      id: "a7",
      type: "mistake",
      text: "Forgot",
      highlight: "Trie Pattern",
      date: daysAgo(3, 18),
    },
    {
      id: "a8",
      type: "quiz-score",
      text: "Quiz Score",
      highlight: "7/10",
      date: daysAgo(4, 21),
    },
    {
      id: "a9",
      type: "solved",
      text: "Solved",
      highlight: "Coin Change",
      date: daysAgo(7, 21),
    },
    {
      id: "a10",
      type: "pattern-mastered",
      text: "Pattern Mastered",
      highlight: "Linked List",
      date: daysAgo(5, 20),
    },
  ],
  revisionQueue: [
    { id: "rq1", type: "question", title: "Minimum Window Substring", completed: false, skipped: false, reviewAgain: false },
    { id: "rq2", type: "question", title: "Longest Repeating Character Replacement", completed: false, skipped: false, reviewAgain: false },
    { id: "rq3", type: "pattern", title: "Trie Pattern", completed: false, skipped: false, reviewAgain: false },
    { id: "rq4", type: "pattern", title: "Graph Traversal", completed: false, skipped: false, reviewAgain: false },
    { id: "rq5", type: "reflection", title: "Window shrinking condition", completed: false, skipped: false, reviewAgain: false },
    { id: "rq6", type: "question", title: "Course Schedule II", completed: false, skipped: false, reviewAgain: false },
    { id: "rq7", type: "question", title: "Implement Trie", completed: false, skipped: false, reviewAgain: false },
    { id: "rq8", type: "question", title: "Word Search", completed: false, skipped: false, reviewAgain: false },
    { id: "rq9", type: "question", title: "Search in Rotated Sorted Array", completed: false, skipped: false, reviewAgain: false },
  ],
  quizResults: [
    { id: "qr1", date: daysAgo(0), score: 8, total: 10 },
    { id: "qr2", date: daysAgo(1), score: 7, total: 10 },
    { id: "qr3", date: daysAgo(2), score: 9, total: 10 },
    { id: "qr4", date: daysAgo(3), score: 6, total: 10 },
    { id: "qr5", date: daysAgo(4), score: 8, total: 10 },
    { id: "qr6", date: daysAgo(5), score: 7, total: 10 },
    { id: "qr7", date: daysAgo(6), score: 9, total: 10 },
  ],
  dailyChallengeIndex: 0,
  dailyChallengeDate: new Date().toISOString().slice(0, 10),
};
